import '../models/weekly_plan.dart';

/// Full Nigerian phonics/literacy curriculum.
/// 6 levels × 3 terms × 13 weeks = 234 weekly plans.
///
/// Level → Class grouping:
///   beginner     = Nursery 1–2
///   elementary   = Nursery 3 – Primary 1
///   intermediate = Primary 2–3
///   upper        = Primary 4–5
///   secondary    = JSS 1–3
///   senior       = SSS 1–3
///
/// Term progression per level:
///   Term 1 = Introduction of core skills
///   Term 2 = Deepening + new extensions
///   Term 3 = Consolidation + application + promotion assessment
class CurriculumMap {
  static List<WeeklyPlan> forLevel(
      String level, {
        int termNumber = 1,
        String termId = '',
        String schoolId = '',
      }) {
    final key = '${level}_term$termNumber';
    final raw = _map[key] ?? _map['${level}_term1'] ?? [];
    return raw.asMap().entries.map((e) {
      final week = e.key + 1;
      final data = e.value;
      return WeeklyPlan(
        id: '$termId-$level-w$week',
        termId: termId,
        schoolId: schoolId,
        weekNumber: week,
        title: data['title'] as String,
        skillTags: List<String>.from(data['skillTags'] as List),
        objectives: List<String>.from(data['objectives'] as List),
        level: level,
      );
    }).toList();
  }

  /// Human-readable label for each level
  static String levelLabel(String level) {
    const labels = {
      'beginner': 'Beginner (Nursery 1–2)',
      'elementary': 'Elementary (Nursery 3 – Primary 1)',
      'intermediate': 'Intermediate (Primary 2–3)',
      'upper': 'Upper (Primary 4–5)',
      'secondary': 'Secondary (JSS 1–3)',
      'senior': 'Senior (SSS 1–3)',
    };
    return labels[level] ?? level;
  }

  static const List<String> levels = [
    'beginner',
    'elementary',
    'intermediate',
    'upper',
    'secondary',
    'senior',
  ];

  static const Map<String, List<Map<String, dynamic>>> _map = {

    // ═══════════════════════════════════════════════════════════════════════
    // BEGINNER — Nursery 1–2
    // ═══════════════════════════════════════════════════════════════════════

    'beginner_term1': [
      { 'title': 'Week 1 — Listening & Environmental Sounds',
        'skillTags': ['rhyme'],
        'objectives': ['Identify and distinguish everyday sounds', 'Clap and move to rhythm and beat', 'Enjoy and join in with nursery rhymes'] },
      { 'title': 'Week 2 — Body Sounds & Clapping',
        'skillTags': ['rhyme', 'alliteration'],
        'objectives': ['Make sounds with body (clap, stomp, tap)', 'Respond to simple sound patterns', 'Begin to notice rhyme in songs'] },
      { 'title': 'Week 3 — Nursery Rhymes',
        'skillTags': ['rhyme'],
        'objectives': ['Join in with familiar nursery rhymes', 'Identify rhyming pairs in rhymes', 'Fill in the missing rhyming word'] },
      { 'title': 'Week 4 — Oral Blending Intro',
        'skillTags': ['oral_blending'],
        'objectives': ['Listen to sounds said slowly and guess the word', 'Blend 2-phoneme words orally (e.g. /m/-/e/ = me)', 'Play "robot talk" games with 2-sound words'] },
      { 'title': 'Week 5 — Initial Sounds (s, a, t)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise and produce /s/, /a/, /t/ sounds', 'Identify objects beginning with s, a, t', 'Trace letters s, a, t with correct formation'] },
      { 'title': 'Week 6 — Initial Sounds (p, i, n)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise and produce /p/, /i/, /n/ sounds', 'Sort pictures by initial sound', 'Trace and copy letters p, i, n'] },
      { 'title': 'Week 7 — Initial Sounds (m, d, g)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise /m/, /d/, /g/ sounds', 'Match letters to pictures', 'Form letters m, d, g in sand/air'] },
      { 'title': 'Week 8 — Initial Sounds (o, c, k)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise /o/, /c/, /k/ sounds', 'Begin to read single letters aloud', 'Trace letters o, c, k'] },
      { 'title': 'Week 9 — Initial Sounds (e, u, r)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise /e/, /u/, /r/ sounds', 'Identify initial sounds in spoken words', 'Begin matching letter to object'] },
      { 'title': 'Week 10 — Initial Sounds (h, b, f)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise /h/, /b/, /f/ sounds', 'Play initial sound sorting game', 'Trace letters h, b, f'] },
      { 'title': 'Week 11 — Rhyme & Alliteration Play',
        'skillTags': ['rhyme', 'alliteration'],
        'objectives': ['Generate own rhyming words orally', 'Identify alliterative pairs', 'Enjoy tongue twisters and rhyming games'] },
      { 'title': 'Week 12 — Oral Blending & Review',
        'skillTags': ['oral_blending', 'letter_sound'],
        'objectives': ['Blend 2–3 phoneme words orally', 'Review all 12 initial sounds taught', 'Recognise and say sounds fluently'] },
      { 'title': 'Week 13 — End-of-Term Celebration',
        'skillTags': ['rhyme', 'letter_sound', 'oral_blending'],
        'objectives': ['Perform a nursery rhyme as a class', 'Complete oral phonics assessment', 'Teacher notes readiness for Term 2'] },
    ],

    'beginner_term2': [
      { 'title': 'Week 1 — Review Term 1 Sounds',
        'skillTags': ['letter_sound'],
        'objectives': ['Fluently produce all Term 1 letter sounds', 'Play rapid sound recognition games', 'Begin to connect sounds to letters in print'] },
      { 'title': 'Week 2 — New Sounds (l, ll, ss)',
        'skillTags': ['letter_sound'],
        'objectives': ['Introduce /l/, double-l, double-s', 'Recognise these in simple words', 'Trace and write l'] },
      { 'title': 'Week 3 — New Sounds (j, v, w, x)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise and produce /j/, /v/, /w/, /x/', 'Match to picture cards', 'Sing the alphabet song'] },
      { 'title': 'Week 4 — New Sounds (y, z, zz, qu)',
        'skillTags': ['letter_sound'],
        'objectives': ['Recognise /y/, /z/, /qu/', 'Complete the alphabet', 'Play letter bingo'] },
      { 'title': 'Week 5 — CVC Blending: -at, -an',
        'skillTags': ['cvc_word', 'oral_blending'],
        'objectives': ['Blend CVC words in -at and -an family', 'Read: cat, mat, hat, can, man, fan', 'Build words with letter cards'] },
      { 'title': 'Week 6 — CVC Blending: -it, -in',
        'skillTags': ['cvc_word'],
        'objectives': ['Read -it and -in word families', 'Identify the short /i/ sound', 'Write 3 CVC words from dictation'] },
      { 'title': 'Week 7 — CVC Blending: -og, -op',
        'skillTags': ['cvc_word'],
        'objectives': ['Read -og and -op word families', 'Identify short /o/', 'Word swap game: change initial letter'] },
      { 'title': 'Week 8 — CVC Blending: -ug, -un',
        'skillTags': ['cvc_word'],
        'objectives': ['Read -ug and -un word families', 'Identify short /u/', 'Write simple CVC sentences'] },
      { 'title': 'Week 9 — Short Vowel Sort',
        'skillTags': ['short_vowel'],
        'objectives': ['Sort pictures by short vowel sound (a, e, i, o, u)', 'Match CVC word to picture', 'Read 10 CVC words with accuracy'] },
      { 'title': 'Week 10 — Short Vowels: Reading Sentences',
        'skillTags': ['short_vowel', 'cvc_word'],
        'objectives': ['Read short sentences using CVC words', 'Point to words left to right', 'Identify capital letters and full stops'] },
      { 'title': 'Week 11 — Rhyme with CVC Words',
        'skillTags': ['rhyme', 'cvc_word'],
        'objectives': ['Generate rhyming CVC words', 'Read a simple rhyming decodable text', 'Illustrate a rhyming pair'] },
      { 'title': 'Week 12 — CVC Fluency & Writing',
        'skillTags': ['cvc_word', 'short_vowel'],
        'objectives': ['Write 10 CVC words unaided', 'Read a short decodable story', 'Peer reading partner activity'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['cvc_word', 'letter_sound', 'short_vowel'],
        'objectives': ['Complete written and oral phonics assessment', 'Teacher notes areas for support', 'Celebrate reading progress'] },
    ],

    'beginner_term3': [
      { 'title': 'Week 1 — Review CVC Words',
        'skillTags': ['cvc_word', 'short_vowel'],
        'objectives': ['Read 20 CVC words with automaticity', 'Spell 10 CVC words from dictation', 'Identify short vowels in isolation'] },
      { 'title': 'Week 2 — Introduction to Digraphs: sh, ch',
        'skillTags': ['digraph'],
        'objectives': ['Recognise sh and ch as two-letter sounds', 'Read: ship, chip, shop, chop', 'Trace and write sh and ch words'] },
      { 'title': 'Week 3 — Digraphs: th, ng',
        'skillTags': ['digraph'],
        'objectives': ['Produce /th/ and /ng/ sounds', 'Read: the, this, ring, sing', 'Blend digraph words'] },
      { 'title': 'Week 4 — High-Frequency Words (set 1)',
        'skillTags': ['cvc_word'],
        'objectives': ['Read and write: I, a, the, to, no, go', 'Use in simple spoken sentences', 'Flash card recognition game'] },
      { 'title': 'Week 5 — High-Frequency Words (set 2)',
        'skillTags': ['cvc_word'],
        'objectives': ['Read and write: is, it, in, on, at, and', 'Read short sentences with HFW + CVC', 'Write 2 sentences using HFW'] },
      { 'title': 'Week 6 — Oral Segmenting',
        'skillTags': ['oral_blending'],
        'objectives': ['Segment spoken words into phonemes', 'Clap syllables in 2-syllable words', 'Play "how many sounds?" game'] },
      { 'title': 'Week 7 — Reading Simple Sentences',
        'skillTags': ['cvc_word', 'digraph'],
        'objectives': ['Read 5-word sentences with CVC and HFW', 'Track print left to right', 'Answer simple comprehension questions'] },
      { 'title': 'Week 8 — Writing Simple Sentences',
        'skillTags': ['cvc_word'],
        'objectives': ['Write a sentence with a capital and full stop', 'Use finger spaces between words', 'Draw and label a picture'] },
      { 'title': 'Week 9 — Consonant Clusters Intro',
        'skillTags': ['consonant_cluster'],
        'objectives': ['Blend initial clusters: st, cl, fl', 'Read: stop, clip, flag', 'Compare CVC vs CCVC words'] },
      { 'title': 'Week 10 — Consonant Clusters: bl, gr, tr',
        'skillTags': ['consonant_cluster'],
        'objectives': ['Blend: bl, gr, tr clusters', 'Read: blog, grab, trip', 'Tongue-twister activity'] },
      { 'title': 'Week 11 — Review & Fluency',
        'skillTags': ['cvc_word', 'digraph', 'consonant_cluster'],
        'objectives': ['Read a short story using all taught patterns', 'Identify digraphs in text', 'Spell 10 words from the year'] },
      { 'title': 'Week 12 — Year Review',
        'skillTags': ['letter_sound', 'cvc_word', 'short_vowel', 'digraph'],
        'objectives': ['Recap all sounds and patterns from the year', 'Play phonics quiz', 'Self-assess reading progress'] },
      { 'title': 'Week 13 — End-of-Year Assessment',
        'skillTags': ['cvc_word', 'short_vowel', 'digraph', 'letter_sound'],
        'objectives': ['Complete end-of-year phonics assessment', 'Teacher identifies readiness for Elementary level', 'Issue progress report'] },
    ],

    // ═══════════════════════════════════════════════════════════════════════
    // ELEMENTARY — Nursery 3 – Primary 1
    // ═══════════════════════════════════════════════════════════════════════

    'elementary_term1': [
      { 'title': 'Week 1 — Review CVC & Initial Sounds',
        'skillTags': ['cvc_word', 'letter_sound'],
        'objectives': ['Read 20 CVC words fluently', 'Identify all 26 letter sounds', 'Spell simple CVC words without support'] },
      { 'title': 'Week 2 — Digraphs: sh, ch, th',
        'skillTags': ['digraph'],
        'objectives': ['Produce and read sh, ch, th', 'Distinguish voiced and unvoiced /th/', 'Read words: shop, chip, that, thin'] },
      { 'title': 'Week 3 — Digraphs: wh, ph, ng, nk',
        'skillTags': ['digraph'],
        'objectives': ['Read wh- words (what, when, where)', 'Introduce ph = /f/ in common words', 'Read -ng and -nk endings'] },
      { 'title': 'Week 4 — Consonant Clusters (initial)',
        'skillTags': ['consonant_cluster'],
        'objectives': ['Blend sl, br, cr, dr, fr clusters', 'Read CCVC words accurately', 'Clap and count phonemes in cluster words'] },
      { 'title': 'Week 5 — Consonant Clusters (final)',
        'skillTags': ['consonant_cluster', 'ccvc_cvcc'],
        'objectives': ['Read final clusters: -nd, -nt, -st, -sk', 'Read CVCC words: land, tent, best', 'Write 5 CVCC words from dictation'] },
      { 'title': 'Week 6 — Long Vowel: ai, ay',
        'skillTags': ['vowel_digraph'],
        'objectives': ['Recognise ai and ay as long /a/ spellings', 'Read: rain, train, day, play', 'Sort ai and ay words'] },
      { 'title': 'Week 7 — Long Vowel: ee, ea',
        'skillTags': ['vowel_digraph'],
        'objectives': ['Recognise ee and ea as long /e/ spellings', 'Read: feet, meet, leaf, beach', 'Identify pattern in reading text'] },
      { 'title': 'Week 8 — Long Vowel: oa, ow',
        'skillTags': ['vowel_digraph'],
        'objectives': ['Recognise oa and ow as long /o/', 'Distinguish ow = /o/ vs ow = /ow/', 'Read a decodable passage'] },
      { 'title': 'Week 9 — R-Controlled: ar, or',
        'skillTags': ['r_controlled'],
        'objectives': ['Produce /ar/ and /or/ sounds', 'Read: farm, car, corn, born', 'Write 6 r-controlled words from dictation'] },
      { 'title': 'Week 10 — R-Controlled: er, ir, ur',
        'skillTags': ['r_controlled'],
        'objectives': ['Understand er, ir, ur all say /ur/', 'Sort by spelling pattern', 'Use context to select correct spelling'] },
      { 'title': 'Week 11 — Reading Sentences',
        'skillTags': ['cvc_word', 'digraph', 'vowel_digraph'],
        'objectives': ['Read 6-word sentences with taught patterns', 'Answer who/what/where comprehension questions', 'Track print fluently'] },
      { 'title': 'Week 12 — Writing Sentences',
        'skillTags': ['cvc_word', 'digraph', 'vowel_digraph'],
        'objectives': ['Write 3 sentences independently', 'Use capital letters and full stops correctly', 'Check and edit own writing'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['digraph', 'vowel_digraph', 'r_controlled', 'consonant_cluster'],
        'objectives': ['Complete end-of-term phonics assessment', 'Review progress and set targets', 'Identify students ready for Intermediate'] },
    ],

    'elementary_term2': [
      { 'title': 'Week 1 — Review Term 1 Patterns',
        'skillTags': ['digraph', 'vowel_digraph', 'r_controlled'],
        'objectives': ['Read 25 words from Term 1 with automaticity', 'Identify vowel digraphs in a reading passage', 'Spell 10 Term 1 words from dictation'] },
      { 'title': 'Week 2 — Long Vowel: oo (short & long)',
        'skillTags': ['vowel_digraph'],
        'objectives': ['Read oo = /oo/ (book) vs oo = /oo/ (moon)', 'Sort words by oo sound', 'Read: cook, look, moon, spoon'] },
      { 'title': 'Week 3 — Long Vowel: oi, oy',
        'skillTags': ['vowel_digraph'],
        'objectives': ['Recognise oi and oy as /oy/ spellings', 'Read: coin, boil, boy, toy', 'Write sentences using oi and oy words'] },
      { 'title': 'Week 4 — Long Vowel: ou, ow',
        'skillTags': ['vowel_digraph'],
        'objectives': ['Recognise ou and ow as /ow/ spellings', 'Read: cloud, mouse, cow, town', 'Sort ow words by sound'] },
      { 'title': 'Week 5 — Split Digraph a_e',
        'skillTags': ['split_digraph'],
        'objectives': ['Understand magic e changes vowel sound', 'Read a_e words: cake, name, late', 'Compare pin/pine, cap/cape'] },
      { 'title': 'Week 6 — Split Digraph i_e, o_e',
        'skillTags': ['split_digraph'],
        'objectives': ['Read i_e words: kite, bike, line', 'Read o_e words: bone, home, note', 'Write CVCe words from dictation'] },
      { 'title': 'Week 7 — Split Digraph u_e, e_e',
        'skillTags': ['split_digraph'],
        'objectives': ['Read u_e and e_e words', 'Recognise all five magic-e patterns', 'Read a decodable text with CVCe words'] },
      { 'title': 'Week 8 — High Frequency Words (primary set)',
        'skillTags': ['cvc_word'],
        'objectives': ['Read and write 20 HFW fluently', 'Use in sentences', 'Speed recognition flash card game'] },
      { 'title': 'Week 9 — Reading for Meaning',
        'skillTags': ['digraph', 'split_digraph', 'vowel_digraph'],
        'objectives': ['Read a short story independently', 'Identify main character and setting', 'Answer 4 comprehension questions'] },
      { 'title': 'Week 10 — Plurals: -s, -es',
        'skillTags': ['suffix'],
        'objectives': ['Add -s and -es to make plurals', 'Understand when to use -es', 'Write plural sentences'] },
      { 'title': 'Week 11 — Adding -ing and -ed',
        'skillTags': ['suffix'],
        'objectives': ['Add -ing to verbs', 'Add -ed to make past tense', 'Apply doubling rule for short vowel verbs'] },
      { 'title': 'Week 12 — Fluency & Writing',
        'skillTags': ['split_digraph', 'vowel_digraph', 'suffix'],
        'objectives': ['Read a page of text fluently', 'Write a short paragraph about a topic', 'Self-check for phonics accuracy'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['split_digraph', 'vowel_digraph', 'suffix', 'r_controlled'],
        'objectives': ['Complete written end-of-term assessment', 'Review and celebrate progress', 'Set targets for Term 3'] },
    ],

    'elementary_term3': [
      { 'title': 'Week 1 — Review Split Digraph & Vowel Digraphs',
        'skillTags': ['split_digraph', 'vowel_digraph'],
        'objectives': ['Read 30 words covering all vowel digraph patterns', 'Spell 12 words from dictation', 'Identify patterns in unknown words'] },
      { 'title': 'Week 2 — Alternative Spellings for /a/',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Map a_e, ai, ay, a to long /a/', 'Use a spelling chart', 'Decode unfamiliar /a/ words'] },
      { 'title': 'Week 3 — Alternative Spellings for /e/ and /i/',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Map ee, ea, e, y to long /e/', 'Map i_e, igh, y to long /i/', 'Word sort by sound and spelling'] },
      { 'title': 'Week 4 — Syllables: Counting & Clapping',
        'skillTags': ['syllable'],
        'objectives': ['Count syllables in 1–3 syllable words', 'Identify stressed syllable', 'Clap names of classmates'] },
      { 'title': 'Week 5 — Syllable Division VC/CV',
        'skillTags': ['syllable'],
        'objectives': ['Divide 2-syllable words using VC/CV rule', 'Read: rabbit, basket, napkin', 'Write 5 divided words'] },
      { 'title': 'Week 6 — Prefixes: un-, re-',
        'skillTags': ['prefix'],
        'objectives': ['Understand un- = not / reverse', 'Understand re- = again', 'Add prefixes to known base words'] },
      { 'title': 'Week 7 — Suffixes: -er, -est, -ly',
        'skillTags': ['suffix'],
        'objectives': ['Add -er and -est for comparison', 'Add -ly for adverbs', 'Use in sentences: quickly, faster, tallest'] },
      { 'title': 'Week 8 — Homophones (basic)',
        'skillTags': ['homophone'],
        'objectives': ['Distinguish: to/two/too, here/hear', 'Use context to choose correct spelling', 'Write sentences with homophones'] },
      { 'title': 'Week 9 — Reading a Full Story',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Read a complete short story independently', 'Summarise beginning, middle, end', 'Read aloud expressively'] },
      { 'title': 'Week 10 — Writing a Story',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Plan and write a 3-sentence story', 'Use at least 2 words with affixes', 'Peer review and revise'] },
      { 'title': 'Week 11 — Spelling Strategies',
        'skillTags': ['alternative_spelling', 'homophone'],
        'objectives': ['Apply look-cover-write-check strategy', 'Use mnemonics for tricky words', 'Compile personal spelling list'] },
      { 'title': 'Week 12 — Year Consolidation',
        'skillTags': ['digraph', 'vowel_digraph', 'split_digraph', 'suffix', 'prefix'],
        'objectives': ['Read 40 words covering all patterns taught', 'Write a paragraph independently', 'Celebrate reading growth'] },
      { 'title': 'Week 13 — End-of-Year Assessment',
        'skillTags': ['alternative_spelling', 'syllable', 'prefix', 'suffix', 'homophone'],
        'objectives': ['Complete end-of-year phonics and literacy assessment', 'Teacher assesses readiness for Intermediate', 'Issue full-year progress report'] },
    ],

    // ═══════════════════════════════════════════════════════════════════════
    // INTERMEDIATE — Primary 2–3
    // ═══════════════════════════════════════════════════════════════════════

    'intermediate_term1': [
      { 'title': 'Week 1 — Review Elementary Patterns',
        'skillTags': ['split_digraph', 'vowel_digraph', 'r_controlled'],
        'objectives': ['Read 30 words fluently', 'Spell 12 words from dictation', 'Identify spelling patterns in a reading passage'] },
      { 'title': 'Week 2 — Alternative Spellings for Long Vowels',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Map all spellings for /a/, /e/, /i/', 'Use a sound-spelling reference chart', 'Decode unfamiliar words using chart'] },
      { 'title': 'Week 3 — Alternative Spellings for /o/ and /u/',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Map o_e, oa, ow, o to /o/', 'Map u_e, ue, ew to /u/', 'Apply to decoding and spelling'] },
      { 'title': 'Week 4 — Syllable Types: Open & Closed',
        'skillTags': ['syllable'],
        'objectives': ['Identify open syllables (CV: me, go)', 'Identify closed syllables (CVC: sit, map)', 'Sort words by syllable type'] },
      { 'title': 'Week 5 — Syllable Division: V/CV & VC/V',
        'skillTags': ['syllable'],
        'objectives': ['Apply V/CV rule (ti-ger)', 'Apply VC/V rule (cab-in)', 'Read 2-syllable words fluently'] },
      { 'title': 'Week 6 — Prefixes: un-, re-, pre-, dis-',
        'skillTags': ['prefix'],
        'objectives': ['Add prefixes to base words', 'Infer word meaning from prefix', 'Write 4 sentences with prefixed words'] },
      { 'title': 'Week 7 — Prefixes: mis-, over-, sub-',
        'skillTags': ['prefix'],
        'objectives': ['Understand mis- = wrongly, over- = too much, sub- = under', 'Match prefix to definition', 'Create new words using prefixes'] },
      { 'title': 'Week 8 — Suffixes: -tion, -sion',
        'skillTags': ['suffix'],
        'objectives': ['Read -tion words: nation, station, action', 'Read -sion words: mansion, tension', 'Spell 5 -tion words correctly'] },
      { 'title': 'Week 9 — Suffixes: -ness, -ful, -less',
        'skillTags': ['suffix'],
        'objectives': ['Add -ness, -ful, -less to adjectives', 'Understand meaning change', 'Use in original sentences'] },
      { 'title': 'Week 10 — Homophones',
        'skillTags': ['homophone'],
        'objectives': ['Distinguish: their/there/they\'re, where/wear/were', 'Use context clues to select correct word', 'Write a paragraph with 4 homophones'] },
      { 'title': 'Week 11 — Reading Comprehension',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Read a 2-paragraph text', 'Answer literal and inferential questions', 'Identify new vocabulary from context'] },
      { 'title': 'Week 12 — Written Composition',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Write a 5-sentence paragraph', 'Use at least 3 words with affixes', 'Edit for spelling and punctuation'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['alternative_spelling', 'syllable', 'prefix', 'suffix', 'homophone'],
        'objectives': ['Complete written assessment', 'Review and reflect on progress', 'Set goals for Term 2'] },
    ],

    'intermediate_term2': [
      { 'title': 'Week 1 — Review & Consolidate',
        'skillTags': ['alternative_spelling', 'prefix', 'suffix'],
        'objectives': ['Rapid recall of spelling patterns', 'Identify prefixes and suffixes in text', 'Spell 15 words from dictation'] },
      { 'title': 'Week 2 — Silent Letters: kn, wr, gn',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Recognise kn = /n/, wr = /r/, gn = /n/', 'Read: know, write, gnaw, kneel', 'Write 5 silent letter words'] },
      { 'title': 'Week 3 — Silent Letters: mb, gh',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Read: lamb, thumb, night, eight', 'Understand historical origin briefly', 'Spell 5 words with mb and gh'] },
      { 'title': 'Week 4 — Compound Words',
        'skillTags': ['syllable'],
        'objectives': ['Identify two base words in a compound', 'Read: football, sunshine, bedroom', 'Create new compound words'] },
      { 'title': 'Week 5 — Contractions',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Understand apostrophe replaces letters', 'Read: can\'t, won\'t, I\'m, they\'re', 'Write expanded and contracted forms'] },
      { 'title': 'Week 6 — Possessive Apostrophe',
        'skillTags': ['suffix'],
        'objectives': ['Distinguish it\'s vs its, who\'s vs whose', 'Add apostrophe-s for possession', 'Correct errors in given sentences'] },
      { 'title': 'Week 7 — Adjectives & Comparatives',
        'skillTags': ['suffix'],
        'objectives': ['Form comparative (-er) and superlative (-est)', 'Apply doubling and drop-e rules', 'Use in written descriptions'] },
      { 'title': 'Week 8 — Adverbs with -ly',
        'skillTags': ['suffix'],
        'objectives': ['Form adverbs from adjectives using -ly', 'Identify adverbs in sentences', 'Write 3 sentences with adverbs'] },
      { 'title': 'Week 9 — More Homophones',
        'skillTags': ['homophone'],
        'objectives': ['Distinguish: passed/past, allowed/aloud, affect/effect', 'Use memory tricks for tricky pairs', 'Context paragraph exercise'] },
      { 'title': 'Week 10 — 3-Syllable Words',
        'skillTags': ['syllable'],
        'objectives': ['Divide 3-syllable words into parts', 'Read: fantastic, umbrella, exciting', 'Clap and count syllables accurately'] },
      { 'title': 'Week 11 — Reading: Non-Fiction',
        'skillTags': ['alternative_spelling', 'suffix', 'prefix'],
        'objectives': ['Read a non-fiction passage', 'Identify key facts and main idea', 'Use new vocabulary in discussion'] },
      { 'title': 'Week 12 — Writing: Non-Fiction Paragraph',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Write a fact-based paragraph with topic sentence', 'Use technical vocabulary', 'Edit for accuracy'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['alternative_spelling', 'syllable', 'suffix', 'homophone'],
        'objectives': ['Complete written and reading assessment', 'Review portfolio', 'Set targets for Term 3'] },
    ],

    'intermediate_term3': [
      { 'title': 'Week 1 — Year Review: Spelling Patterns',
        'skillTags': ['alternative_spelling', 'split_digraph'],
        'objectives': ['Comprehensive spelling pattern review', 'Identify and correct errors in a passage', 'Spell 20 words from dictation'] },
      { 'title': 'Week 2 — Word Families & Roots',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Identify base words within a word family', 'Understand: act → action → react → active', 'Build word family trees'] },
      { 'title': 'Week 3 — Greek & Latin Roots (intro)',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Introduce tele-, bio-, photo-', 'Read: telephone, biology, photograph', 'Match roots to meanings'] },
      { 'title': 'Week 4 — Vocabulary: Synonyms & Antonyms',
        'skillTags': ['homophone'],
        'objectives': ['Identify synonyms in context', 'Identify antonyms using un- and dis-', 'Use a thesaurus to expand vocabulary'] },
      { 'title': 'Week 5 — Punctuation for Effect',
        'skillTags': ['suffix'],
        'objectives': ['Use exclamation marks and question marks correctly', 'Identify direct speech punctuation', 'Rewrite text with correct punctuation'] },
      { 'title': 'Week 6 — Reading: Fiction',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Read a short story chapter independently', 'Identify plot, character, and setting', 'Make predictions'] },
      { 'title': 'Week 7 — Writing: Narrative',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling'],
        'objectives': ['Write a 2-paragraph story with a beginning and middle', 'Use varied vocabulary including affixed words', 'Peer review'] },
      { 'title': 'Week 8 — Poetry & Rhyme',
        'skillTags': ['rhyme', 'alliteration'],
        'objectives': ['Read and discuss a poem', 'Identify rhyme scheme', 'Write a 4-line poem with a rhyme scheme'] },
      { 'title': 'Week 9 — Spelling Strategies Revision',
        'skillTags': ['alternative_spelling', 'homophone'],
        'objectives': ['Apply look-cover-write-check to 15 words', 'Create mnemonics for tricky words', 'Compile year spelling list'] },
      { 'title': 'Week 10 — Oral Presentation',
        'skillTags': ['syllable'],
        'objectives': ['Prepare and deliver a 1-minute talk', 'Speak in complete sentences', 'Use new vocabulary from the term'] },
      { 'title': 'Week 11 — Comprehension Strategies',
        'skillTags': ['alternative_spelling', 'prefix'],
        'objectives': ['Skim and scan for information', 'Infer meaning from context', 'Summarise a paragraph in one sentence'] },
      { 'title': 'Week 12 — Year Consolidation',
        'skillTags': ['alternative_spelling', 'syllable', 'prefix', 'suffix', 'homophone'],
        'objectives': ['Complete a mixed phonics and literacy activity', 'Read aloud with expression and accuracy', 'Celebrate the year\'s achievements'] },
      { 'title': 'Week 13 — End-of-Year Assessment',
        'skillTags': ['alternative_spelling', 'syllable', 'prefix', 'suffix', 'homophone'],
        'objectives': ['Complete comprehensive literacy assessment', 'Teacher assesses readiness for Upper level', 'Issue full progress report'] },
    ],

    // ═══════════════════════════════════════════════════════════════════════
    // UPPER — Primary 4–5
    // ═══════════════════════════════════════════════════════════════════════

    'upper_term1': [
      { 'title': 'Week 1 — Morphology: Base Words & Affixes',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Analyse complex words by morpheme', 'Identify base + prefix + suffix', 'Infer meaning from morphemic analysis'] },
      { 'title': 'Week 2 — Latin Roots: port, rupt, dict',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Learn port = carry, rupt = break, dict = say', 'Read: transport, disrupt, predict', 'Build new words from each root'] },
      { 'title': 'Week 3 — Latin Roots: vis, aud, scrib',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Learn vis = see, aud = hear, scrib = write', 'Read: vision, audible, describe', 'Use in academic sentences'] },
      { 'title': 'Week 4 — Greek Roots: graph, phon, scope',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Learn graph = write, phon = sound, scope = see', 'Read: photograph, phonics, telescope', 'Match roots to meanings'] },
      { 'title': 'Week 5 — Multi-Syllable Decoding',
        'skillTags': ['syllable'],
        'objectives': ['Decode 4-syllable words by chunking', 'Read: independent, electricity, conversation', 'Apply stress patterns'] },
      { 'title': 'Week 6 — Spelling: Doubling & Drop-e Rules',
        'skillTags': ['suffix'],
        'objectives': ['Apply doubling rule for VCC words', 'Apply drop-e rule before vowel suffixes', 'Spell 10 complex words from dictation'] },
      { 'title': 'Week 7 — Spelling: -ible vs -able',
        'skillTags': ['suffix'],
        'objectives': ['Understand when to use -ible vs -able', 'Read: possible, visible, comfortable, capable', 'Practise 8 words per spelling'] },
      { 'title': 'Week 8 — Spelling: -tion vs -sion vs -cion',
        'skillTags': ['suffix'],
        'objectives': ['Distinguish -tion, -sion, -cion patterns', 'Read: nation, tension, suspicion', 'Write sentences with 2 of each'] },
      { 'title': 'Week 9 — Homophones & Confused Words',
        'skillTags': ['homophone'],
        'objectives': ['Distinguish: principal/principle, stationery/stationary', 'Apply in editing exercises', 'Use dictionary for verification'] },
      { 'title': 'Week 10 — Reading: Extended Fiction',
        'skillTags': ['syllable', 'alternative_spelling'],
        'objectives': ['Read 2 pages of a chapter book', 'Identify theme and author\'s purpose', 'Respond in writing with evidence'] },
      { 'title': 'Week 11 — Writing: Structured Essay Intro',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Write an introductory paragraph with a topic sentence', 'Use transition words', 'Incorporate vocabulary from roots studied'] },
      { 'title': 'Week 12 — Grammar: Verb Tenses',
        'skillTags': ['suffix'],
        'objectives': ['Identify simple, past, and future tenses', 'Convert sentences between tenses', 'Apply in own writing'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['prefix', 'suffix', 'syllable', 'homophone'],
        'objectives': ['Complete written assessment', 'Read aloud a set passage', 'Review and set targets'] },
    ],

    'upper_term2': [
      { 'title': 'Week 1 — Review Roots & Morphology',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Rapid root identification exercise', 'Build 10 new words from studied roots', 'Spell 15 words from dictation'] },
      { 'title': 'Week 2 — More Latin Roots: tract, struct, ject',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Learn tract = pull, struct = build, ject = throw', 'Read: subtract, construct, inject, reject', 'Use in sentences'] },
      { 'title': 'Week 3 — More Greek Roots: chron, geo, bio',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Learn chron = time, geo = earth, bio = life', 'Read: chronology, geography, biology', 'Create word webs'] },
      { 'title': 'Week 4 — Complex Suffixes: -ous, -ious, -eous',
        'skillTags': ['suffix'],
        'objectives': ['Read: famous, glorious, gorgeous', 'Identify base word changes when suffix is added', 'Spell 6 -ous words'] },
      { 'title': 'Week 5 — Complex Suffixes: -ment, -ance, -ence',
        'skillTags': ['suffix'],
        'objectives': ['Add -ment, -ance, -ence to verbs/adjectives', 'Understand meaning shift', 'Spot in non-fiction text'] },
      { 'title': 'Week 6 — Persuasive Writing: Techniques',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Identify persuasive vocabulary', 'Use words like: significant, essential, vital', 'Write a persuasive opening paragraph'] },
      { 'title': 'Week 7 — Formal vs Informal Language',
        'skillTags': ['alternative_spelling', 'suffix'],
        'objectives': ['Distinguish formal and informal register', 'Rewrite informal passage in formal English', 'Use academic vocabulary'] },
      { 'title': 'Week 8 — Reading: Non-Fiction (Science/Social)',
        'skillTags': ['syllable', 'prefix'],
        'objectives': ['Read a 3-paragraph non-fiction text', 'Identify key vocabulary from context', 'Summarise in 3 bullet points'] },
      { 'title': 'Week 9 — Writing: Report Structure',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Write a 3-paragraph factual report', 'Use subheadings and topic sentences', 'Incorporate domain-specific vocabulary'] },
      { 'title': 'Week 10 — Complex Homophones',
        'skillTags': ['homophone'],
        'objectives': ['Distinguish: complement/compliment, desert/dessert', 'Apply in editing tasks', 'Compile a personal homophones guide'] },
      { 'title': 'Week 11 — Punctuation: Commas & Semicolons',
        'skillTags': ['suffix'],
        'objectives': ['Use commas in lists and clauses', 'Introduce semicolons for connected sentences', 'Edit a passage for comma use'] },
      { 'title': 'Week 12 — Oral Language: Debate',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Prepare a 2-minute argument', 'Use persuasive vocabulary', 'Respond to the opposing view politely'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['prefix', 'suffix', 'syllable', 'homophone', 'alternative_spelling'],
        'objectives': ['Complete written and reading comprehension assessment', 'Review and celebrate progress', 'Set Term 3 goals'] },
    ],

    'upper_term3': [
      { 'title': 'Week 1 — Year Spelling Review',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling'],
        'objectives': ['Complete comprehensive spelling review', 'Identify personal spelling patterns to improve', 'Spell 20 words from the year'] },
      { 'title': 'Week 2 — Advanced Root Families',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Map root families: spec, sens, mit/miss', 'Read: specify, sensation, transmit, dismiss', 'Create root-family word maps'] },
      { 'title': 'Week 3 — Vocabulary in Context',
        'skillTags': ['alternative_spelling', 'homophone'],
        'objectives': ['Use context clues to infer unfamiliar word meaning', 'Replace vague words with precise alternatives', 'Build academic vocabulary list'] },
      { 'title': 'Week 4 — Writing: Narrative Composition',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Write a 3-paragraph story with rising tension', 'Use varied sentence structures', 'Include at least 5 complex vocabulary words'] },
      { 'title': 'Week 5 — Writing: Argumentative Essay',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Structure: introduction, argument, counter-argument, conclusion', 'Use discourse markers', 'Edit for cohesion and accuracy'] },
      { 'title': 'Week 6 — Reading Comprehension: Poetry',
        'skillTags': ['rhyme', 'alliteration'],
        'objectives': ['Analyse a poem for rhyme, rhythm, and imagery', 'Identify literary devices', 'Write an analytical response'] },
      { 'title': 'Week 7 — Reading Comprehension: Prose',
        'skillTags': ['syllable', 'alternative_spelling'],
        'objectives': ['Read a longer extract', 'Analyse character and theme', 'Write a paragraph response using evidence'] },
      { 'title': 'Week 8 — Grammar: Complex Sentences',
        'skillTags': ['suffix'],
        'objectives': ['Identify main and subordinate clauses', 'Use subordinating conjunctions', 'Write 5 complex sentences'] },
      { 'title': 'Week 9 — Spelling for Secondary Readiness',
        'skillTags': ['alternative_spelling', 'prefix', 'suffix'],
        'objectives': ['Spell 25 words from the JSS word list', 'Identify spelling strategies for unfamiliar words', 'Practice exam-style spelling'] },
      { 'title': 'Week 10 — Oral: Presentation & Discussion',
        'skillTags': ['syllable'],
        'objectives': ['Deliver a 3-minute prepared presentation', 'Answer questions from peers', 'Use academic vocabulary throughout'] },
      { 'title': 'Week 11 — Mock Assessment Practice',
        'skillTags': ['prefix', 'suffix', 'homophone', 'alternative_spelling'],
        'objectives': ['Complete a mock end-of-year literacy paper', 'Review answers and identify error patterns', 'Practise under timed conditions'] },
      { 'title': 'Week 12 — Year Consolidation',
        'skillTags': ['prefix', 'suffix', 'syllable', 'alternative_spelling', 'homophone'],
        'objectives': ['Complete a portfolio reflection', 'Celebrate literacy achievements', 'Peer-share best written work from the year'] },
      { 'title': 'Week 13 — End-of-Year Assessment',
        'skillTags': ['prefix', 'suffix', 'syllable', 'alternative_spelling', 'homophone'],
        'objectives': ['Complete comprehensive end-of-year assessment', 'Teacher assesses readiness for Secondary level', 'Issue full progress report'] },
    ],

    // ═══════════════════════════════════════════════════════════════════════
    // SECONDARY — JSS 1–3
    // ═══════════════════════════════════════════════════════════════════════

    'secondary_term1': [
      { 'title': 'Week 1 — Academic Vocabulary: Latin Roots',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Master 20 high-frequency Latin roots', 'Analyse academic words morphemically', 'Use in essay writing'] },
      { 'title': 'Week 2 — Academic Vocabulary: Greek Roots',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Master 20 high-frequency Greek roots', 'Read subject-specific vocabulary', 'Create vocabulary notebooks'] },
      { 'title': 'Week 3 — Spelling: Unstressed Vowels',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Recognise schwa sound in unstressed syllables', 'Spell: separate, different, interest', 'Apply in written work'] },
      { 'title': 'Week 4 — Spelling: Double Consonants',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Apply rules for consonant doubling', 'Spell: necessary, occasion, accommodation', 'Memorise common doubles'] },
      { 'title': 'Week 5 — Advanced Suffixes: -ify, -ise, -ate',
        'skillTags': ['suffix'],
        'objectives': ['Form verbs with -ify, -ise, -ate', 'Read: clarify, organise, celebrate', 'Use in formal writing'] },
      { 'title': 'Week 6 — Advanced Prefixes: inter-, trans-, super-',
        'skillTags': ['prefix'],
        'objectives': ['Understand inter-, trans-, super- meanings', 'Read: international, transform, superior', 'Use in academic sentences'] },
      { 'title': 'Week 7 — Reading: Comprehension Strategies',
        'skillTags': ['syllable', 'alternative_spelling'],
        'objectives': ['Apply SQ3R reading strategy', 'Identify main idea and supporting details', 'Make inferences and predictions'] },
      { 'title': 'Week 8 — Writing: Essay Structure',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Write a structured 5-paragraph essay', 'Use topic sentences and transitions', 'Incorporate academic vocabulary'] },
      { 'title': 'Week 9 — Grammar: Passive Voice',
        'skillTags': ['suffix'],
        'objectives': ['Identify passive constructions', 'Convert active to passive', 'Use passive appropriately in formal writing'] },
      { 'title': 'Week 10 — Grammar: Reported Speech',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Convert direct speech to reported speech', 'Apply tense backshift rules', 'Write reported speech accurately'] },
      { 'title': 'Week 11 — Homophones & Confused Words (advanced)',
        'skillTags': ['homophone'],
        'objectives': ['Distinguish: advice/advise, practice/practise', 'Apply in editing complex paragraphs', 'Build master confused-words list'] },
      { 'title': 'Week 12 — Reading: Literature Extract',
        'skillTags': ['alternative_spelling', 'prefix'],
        'objectives': ['Read an extract from a set text', 'Analyse language choices', 'Write a literary response paragraph'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone', 'syllable'],
        'objectives': ['Complete written assessment', 'Comprehension and vocabulary test', 'Review and set targets'] },
    ],

    'secondary_term2': [
      { 'title': 'Week 1 — Review Academic Vocabulary',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Rapid recall of all roots from Term 1', 'Identify in subject-specific texts', 'Spell 20 academic words'] },
      { 'title': 'Week 2 — Etymology: Word Origins',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Explore origins of English words', 'Compare British and Nigerian English vocabulary', 'Use etymology to spell unfamiliar words'] },
      { 'title': 'Week 3 — Spelling: -ei vs -ie',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Apply i before e except after c rule', 'Learn exceptions: weird, seize, protein', 'Spell 10 ie/ei words correctly'] },
      { 'title': 'Week 4 — Register & Tone in Writing',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Identify formal, neutral, and informal register', 'Rewrite texts in different registers', 'Apply appropriate tone in essays'] },
      { 'title': 'Week 5 — Figurative Language',
        'skillTags': ['alliteration'],
        'objectives': ['Identify simile, metaphor, personification, alliteration', 'Analyse effect in context', 'Use figurative language in own writing'] },
      { 'title': 'Week 6 — Reading: Newspaper/Media Text',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Analyse features of newspaper articles', 'Identify bias and perspective', 'Compare two articles on same topic'] },
      { 'title': 'Week 7 — Writing: Formal Letter',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Write a formal complaint or application letter', 'Use correct letter format', 'Apply formal vocabulary and tone'] },
      { 'title': 'Week 8 — Writing: Speech',
        'skillTags': ['alliteration', 'prefix'],
        'objectives': ['Write a 3-paragraph speech', 'Use rhetorical devices: rule of three, direct address', 'Deliver to the class'] },
      { 'title': 'Week 9 — Advanced Homophones',
        'skillTags': ['homophone'],
        'objectives': ['Master: canvas/canvass, born/borne, licence/license', 'Apply in editing tasks', 'Create visual memory aids'] },
      { 'title': 'Week 10 — Grammar: Relative Clauses',
        'skillTags': ['suffix'],
        'objectives': ['Identify and write defining and non-defining relative clauses', 'Use who, which, that, whose correctly', 'Punctuate non-defining clauses'] },
      { 'title': 'Week 11 — Vocabulary: Subject-Specific (Science)',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Learn 15 Science-specific vocabulary items', 'Analyse morphemic structure', 'Use in science writing task'] },
      { 'title': 'Week 12 — Oral: Structured Academic Discussion',
        'skillTags': ['syllable'],
        'objectives': ['Lead a structured discussion using evidence', 'Use academic discourse markers', 'Respond to and extend peers\' ideas'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone'],
        'objectives': ['Complete comprehension, vocabulary, and writing assessment', 'Review and celebrate progress', 'Plan Term 3 focus areas'] },
    ],

    'secondary_term3': [
      { 'title': 'Week 1 — Comprehensive Spelling Review',
        'skillTags': ['alternative_spelling', 'prefix', 'suffix'],
        'objectives': ['Identify and correct personal spelling errors', 'Practise 25 high-frequency academic words', 'Use spelling patterns confidently'] },
      { 'title': 'Week 2 — Advanced Morphology',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Analyse words with 3+ morphemes', 'Read: unimaginable, misrepresentation', 'Infer meaning of new complex words'] },
      { 'title': 'Week 3 — Critical Reading',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Evaluate author\'s argument and evidence', 'Identify assumptions and logical fallacies', 'Write a critical response'] },
      { 'title': 'Week 4 — Exam Writing Skills',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Plan and write under timed conditions', 'Use PEE paragraph structure (Point, Evidence, Explain)', 'Practice with past questions'] },
      { 'title': 'Week 5 — Vocabulary: Subject-Specific (Social Studies)',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Learn 15 Social Studies vocabulary items', 'Analyse and spell accurately', 'Use in argumentative writing'] },
      { 'title': 'Week 6 — Writing: Discursive Essay',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling'],
        'objectives': ['Write a balanced discursive essay', 'Present multiple perspectives with evidence', 'Use hedging language: may, might, could'] },
      { 'title': 'Week 7 — Literature: Analysing Theme',
        'skillTags': ['alliteration', 'rhyme'],
        'objectives': ['Identify and discuss theme in a text', 'Support analysis with textual evidence', 'Compare themes across two texts'] },
      { 'title': 'Week 8 — Reading: Summary Skills',
        'skillTags': ['syllable', 'alternative_spelling'],
        'objectives': ['Summarise a complex text in 100 words', 'Use paraphrasing strategies', 'Maintain key points without copying'] },
      { 'title': 'Week 9 — Mock Examination Practice',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone'],
        'objectives': ['Complete a full mock English Language paper', 'Review errors by category', 'Focus on highest-impact improvements'] },
      { 'title': 'Week 10 — Oral: Formal Presentation',
        'skillTags': ['syllable'],
        'objectives': ['Deliver a 5-minute prepared presentation', 'Use slides or visual aids', 'Handle Q&A session confidently'] },
      { 'title': 'Week 11 — Final Exam Preparation',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone', 'syllable'],
        'objectives': ['Review all skills from the year', 'Identify and address final weak areas', 'Confidence-building session'] },
      { 'title': 'Week 12 — Year Celebration',
        'skillTags': ['rhyme', 'alliteration'],
        'objectives': ['Share best work from the year', 'Peer appreciation activity', 'Reflect on growth and set SSS goals'] },
      { 'title': 'Week 13 — End-of-Year Assessment',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone', 'syllable'],
        'objectives': ['Complete comprehensive assessment', 'Teacher assesses readiness for Senior level', 'Issue full progress report'] },
    ],

    // ═══════════════════════════════════════════════════════════════════════
    // SENIOR — SSS 1–3
    // ═══════════════════════════════════════════════════════════════════════

    'senior_term1': [
      { 'title': 'Week 1 — Advanced Academic Vocabulary',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Master 25 WAEC/NECO high-frequency vocabulary items', 'Analyse word structure and meaning', 'Apply in academic writing'] },
      { 'title': 'Week 2 — Sophisticated Morphology',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Analyse words with 4+ morphemes', 'Infer meaning of specialist vocabulary in context', 'Build subject vocabulary notebooks'] },
      { 'title': 'Week 3 — Spelling: Common Examination Errors',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Identify and correct the 50 most commonly misspelled words in WAEC', 'Memorise spelling patterns', 'Apply in practice essays'] },
      { 'title': 'Week 4 — Reading: Literary Prose',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Read and analyse a prose extract at WAEC level', 'Comment on language, structure, and form', 'Write a structured literary response'] },
      { 'title': 'Week 5 — Reading: Poetry Analysis',
        'skillTags': ['rhyme', 'alliteration'],
        'objectives': ['Analyse a poem: rhyme, rhythm, imagery, tone', 'Identify speaker and context', 'Write a full analytical essay on a poem'] },
      { 'title': 'Week 6 — Writing: Expository Essay',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Write a well-structured expository essay', 'Use academic register throughout', 'Incorporate advanced vocabulary naturally'] },
      { 'title': 'Week 7 — Writing: Letter of Application',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Write a formal letter of application for a position', 'Use correct format and professional tone', 'Demonstrate advanced vocabulary'] },
      { 'title': 'Week 8 — Grammar: Sentence Variety',
        'skillTags': ['suffix'],
        'objectives': ['Use simple, compound, complex, and compound-complex sentences', 'Vary sentence openers', 'Analyse published prose for sentence variety'] },
      { 'title': 'Week 9 — Grammar: Tense Consistency',
        'skillTags': ['suffix'],
        'objectives': ['Maintain consistent tense throughout a piece of writing', 'Identify and correct tense errors', 'Apply in exam-style essay'] },
      { 'title': 'Week 10 — Comprehension: Inference & Deduction',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Answer inferential comprehension questions accurately', 'Use evidence to support deductions', 'Practice WAEC comprehension format'] },
      { 'title': 'Week 11 — Vocabulary: Abstract Nouns & Nominalisation',
        'skillTags': ['suffix'],
        'objectives': ['Form abstract nouns from verbs and adjectives', 'Use nominalisation in formal writing', 'Identify in academic texts'] },
      { 'title': 'Week 12 — Oral: Debate & Argumentation',
        'skillTags': ['alliteration'],
        'objectives': ['Construct a formal debate argument', 'Use rhetorical devices effectively', 'Respond to opposition with evidence'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone', 'syllable'],
        'objectives': ['Complete WAEC-format assessment', 'Review and plan improvement areas', 'Set specific Term 2 targets'] },
    ],

    'senior_term2': [
      { 'title': 'Week 1 — Review & Build Vocabulary Bank',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling'],
        'objectives': ['Review all Term 1 vocabulary', 'Add 25 new academic words to vocabulary bank', 'Use in multiple contexts'] },
      { 'title': 'Week 2 — Advanced Etymology',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Trace etymology of complex academic words', 'Understand Latin, Greek, French influences on English', 'Apply to decoding specialist text'] },
      { 'title': 'Week 3 — Cohesion & Coherence in Writing',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Use cohesive devices: reference, substitution, ellipsis', 'Ensure logical flow between paragraphs', 'Edit sample essays for coherence'] },
      { 'title': 'Week 4 — Reading: Drama/Play Extract',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Read and analyse a dramatic extract', 'Comment on characterisation through dialogue', 'Write a comparative analysis'] },
      { 'title': 'Week 5 — Writing: Narrative Composition (Advanced)',
        'skillTags': ['alliteration', 'suffix'],
        'objectives': ['Write a sophisticated narrative with complex characterisation', 'Use symbolism and foreshadowing', 'Apply varied narrative techniques'] },
      { 'title': 'Week 6 — Writing: Report & Summary',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Write a formal report with executive summary', 'Use passive voice and impersonal structures', 'Demonstrate advanced vocabulary'] },
      { 'title': 'Week 7 — Grammar: Modality',
        'skillTags': ['alternative_spelling'],
        'objectives': ['Use modal verbs accurately for different degrees of certainty', 'Apply hedging language in academic writing', 'Identify modal use in published texts'] },
      { 'title': 'Week 8 — Grammar: Conditionals',
        'skillTags': ['suffix'],
        'objectives': ['Use 1st, 2nd, and 3rd conditionals accurately', 'Apply in argumentative writing', 'Identify conditional structures in literature'] },
      { 'title': 'Week 9 — WAEC Comprehension Practice',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Complete 2 WAEC-format comprehension exercises', 'Apply mark-scheme strategies', 'Review errors and improve technique'] },
      { 'title': 'Week 10 — WAEC Essay Practice',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling'],
        'objectives': ['Write a full WAEC-format essay under timed conditions', 'Apply assessment criteria', 'Peer-mark using mark scheme'] },
      { 'title': 'Week 11 — Vocabulary: Field-Specific (Commerce/Science)',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Acquire 15 subject-specific vocabulary items', 'Analyse morphemic structure', 'Apply in cross-curricular writing'] },
      { 'title': 'Week 12 — Oral: Prepared & Unprepared Speech',
        'skillTags': ['syllable'],
        'objectives': ['Deliver a prepared 5-minute speech', 'Respond to unprepared discussion questions', 'Evaluate own and peers\' oral performance'] },
      { 'title': 'Week 13 — End-of-Term Assessment',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone'],
        'objectives': ['Complete full WAEC-format mock paper', 'Detailed review of all sections', 'Final targets for Term 3'] },
    ],

    'senior_term3': [
      { 'title': 'Week 1 — Final Vocabulary Consolidation',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling'],
        'objectives': ['Master the full academic vocabulary bank', 'Speed-read and identify unknown words', 'Apply strategies for unseen vocabulary'] },
      { 'title': 'Week 2 — WAEC Comprehension: Full Technique',
        'skillTags': ['alternative_spelling', 'syllable'],
        'objectives': ['Master all question types: summary, vocabulary, inference', 'Apply time-management strategies', 'Complete 2 full comprehension papers'] },
      { 'title': 'Week 3 — WAEC Essay: All Types',
        'skillTags': ['prefix', 'suffix'],
        'objectives': ['Practise expository, narrative, argumentative, and descriptive essay types', 'Apply WAEC marking criteria', 'Peer assess using mark scheme'] },
      { 'title': 'Week 4 — WAEC Letter Writing',
        'skillTags': ['suffix', 'prefix'],
        'objectives': ['Practise formal and informal letter formats', 'Address common letter prompts from past papers', 'Perfect layout and tone'] },
      { 'title': 'Week 5 — Literature Revision',
        'skillTags': ['rhyme', 'alliteration', 'alternative_spelling'],
        'objectives': ['Revise set texts for literature paper', 'Practise essay and extract questions', 'Apply analytical vocabulary accurately'] },
      { 'title': 'Week 6 — Grammar: Full Revision',
        'skillTags': ['suffix', 'prefix', 'alternative_spelling'],
        'objectives': ['Review all grammar topics from the three years', 'Complete grammar diagnostic test', 'Target areas of weakness'] },
      { 'title': 'Week 7 — Mock WAEC: Paper 1',
        'skillTags': ['alternative_spelling', 'prefix', 'suffix', 'homophone'],
        'objectives': ['Complete a full mock Paper 1 under exam conditions', 'Mark and review with teacher', 'Plan final improvements'] },
      { 'title': 'Week 8 — Mock WAEC: Paper 2',
        'skillTags': ['prefix', 'suffix', 'alliteration', 'rhyme'],
        'objectives': ['Complete a full mock Paper 2 under exam conditions', 'Mark and review with teacher', 'Identify final areas to consolidate'] },
      { 'title': 'Week 9 — Targeted Revision',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone'],
        'objectives': ['Personalised revision based on mock exam results', 'Focus on highest-impact improvements', 'Confidence-building activity'] },
      { 'title': 'Week 10 — Oral English Preparation',
        'skillTags': ['syllable'],
        'objectives': ['Practise oral English test format', 'Focus on stress, rhythm, and intonation', 'Mock oral examination'] },
      { 'title': 'Week 11 — Final Examination Preparation',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone', 'syllable'],
        'objectives': ['Final comprehensive review of all topics', 'Exam technique and time management', 'Positive exam mindset session'] },
      { 'title': 'Week 12 — Celebration & Reflection',
        'skillTags': ['rhyme', 'alliteration'],
        'objectives': ['Share and celebrate best work from the three years', 'Reflect on literacy journey', 'Set goals for tertiary education'] },
      { 'title': 'Week 13 — End-of-Year Assessment',
        'skillTags': ['prefix', 'suffix', 'alternative_spelling', 'homophone', 'syllable'],
        'objectives': ['Complete final assessment', 'Issue comprehensive progress report', 'Farewell and future goals session'] },
    ],
  };
}